#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

ini_set('date.timezone','Asia/Shanghai');

if(file_exists(__DIR__ . '/config-test')) {
    defined('YII_DEBUG') or define('YII_DEBUG', true);
    defined('YII_ENV') or define('YII_ENV', 'dev');
} else {
    defined('YII_DEBUG') or define('YII_DEBUG', false);
    defined('YII_ENV') or define('YII_ENV', 'pro');
}

define('VENDOR_PATH', __DIR__ . '/library/vendor');
// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

// error_reporting(0);
 error_reporting(E_ALL);
// ini_set('display_errors', 'Off');

require(VENDOR_PATH . '/autoload.php');
require(VENDOR_PATH . '/yiisoft/yii2/Yii.php');
require(VENDOR_PATH . '/../sqExt/base/JYii.php');

if(YII_ENV == 'dev') {
    $config = include(__DIR__ . '/config-test/console.php');
} else {
    $config = include(__DIR__ . '/config/console.php');
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
